### ISSUE TITLE
Access to the git submodules

### ISSUE THREAD

**Issue by NickGreen** [EssentialBlocks/countdown-block#3]
Hey y'all! I've got a custom implementation that I've had to build for one of my sites based on your great plugin, and I need to be able to build the files for the plugin.

I was hoping to update the plugin, but that means I need access to the submodules designated in the .gitmodules file, which appear to be 404'ing for me. ( EssentialBlocks/style-handler and EssentialBlocks/controls )

Any suggestions for how I can run build on this, without access to those? Or perhaps you could make those submodules public?

Many thanks for your awesome plugin.

**Comment by NickGreen** [comment]
cc: @Rahat89

**Comment by NickGreen** [comment]
Also noted that the 1.0.4 release zip includes the src and util files, which is super helpful. You might also consider including those in the 1.1.0 release files.

**Comment by khan-rafin-ahmed** [comment]
Hi @NickGreen,

First of all, I am glad to know that you are enjoying using our Countdown block. 

However, because of development concerns, we are actually unable to share access to the private repos of ssentialBlocks/style-handler and EssentialBlocks/controls. I hope you understand.

On the other hand, you can actually let us know what feature you were looking for in our Countdown block. If that makes a lot of sense for us and would be helpful for other users, we would definitely try to implement it in our block as well.

I am looking forward to hearing from you soon.

Thank you!

**Comment by NickGreen** [comment]
Ah, OK, I understand. It's too bad you decided to shut it down since the last release, but it is what it is. 

The feature that I've added is pretty specific to the partners I'm working with - it's a feature to allow it to countdown to the next event in their Google Calendar, on a rolling basis. 

Maybe if y'all added a filter for the timestamp that the countdown block is counting down to, then we could potentially build on top of that. But in the mean time, I'll just stick with what I have. 

Best regards.
